#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
yarn type:check

AUTHORS=(
  'learn_fc:learn_fc@gmail.com'
)

# AUTHOR_CONFIG="$GIT_AUTHOR_NAME:$GIT_AUTHOR_EMAIL"

# if [[ ! " ${AUTHORS[*]} " =~ " ${AUTHOR_CONFIG} " ]]; then
#   echo ⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫
#   echo "Your name should be the same as your username."
#   echo "Example: learn_fc <learn_fc@gmail.com>"
#   echo
#   echo "Fix your username by using:"
#   echo "git config user.name learn_fc"
#   echo "git config user.email learn_fc@gmail.com"
#   echo "Then try commiting again"
#   echo ⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫⛔️🚫
#   exit 1
# fi